// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0GlFQiklvbtqfa9O0Qqe8JMIUONZEBE0',
    appId: '1:785179235072:web:927d131659f5144dad19e5',
    messagingSenderId: '785179235072',
    projectId: 'alu-internship-66341',
    authDomain: 'alu-internship-66341.firebaseapp.com',
    storageBucket: 'alu-internship-66341.firebasestorage.app',
    measurementId: 'G-ZSGVH72XHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIDTU0mvvRWM6I0L-1FGZDiiPVk3z5TOU',
    appId: '1:785179235072:android:8a77c58bf32fbea1ad19e5',
    messagingSenderId: '785179235072',
    projectId: 'alu-internship-66341',
    storageBucket: 'alu-internship-66341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmICYyDjYfALYkL-OsZTbGXlHKUHkBmuw',
    appId: '1:785179235072:ios:cddece4dc96461e9ad19e5',
    messagingSenderId: '785179235072',
    projectId: 'alu-internship-66341',
    storageBucket: 'alu-internship-66341.firebasestorage.app',
    iosBundleId: 'com.example.aluInternship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmICYyDjYfALYkL-OsZTbGXlHKUHkBmuw',
    appId: '1:785179235072:ios:cddece4dc96461e9ad19e5',
    messagingSenderId: '785179235072',
    projectId: 'alu-internship-66341',
    storageBucket: 'alu-internship-66341.firebasestorage.app',
    iosBundleId: 'com.example.aluInternship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0GlFQiklvbtqfa9O0Qqe8JMIUONZEBE0',
    appId: '1:785179235072:web:1efd94a44d92b0abad19e5',
    messagingSenderId: '785179235072',
    projectId: 'alu-internship-66341',
    authDomain: 'alu-internship-66341.firebaseapp.com',
    storageBucket: 'alu-internship-66341.firebasestorage.app',
    measurementId: 'G-L0F74QFBPR',
  );
}
